spring:
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 200MB #最大请求文件的大小
      max-file-size: 200MB #设置单个文件最大长度
  datasource:
    url: jdbc:mysql://localhost:3306/price_statistics?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 2283392Byh
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  type-enums-package: tutu.njr10byh.price_statistics.enums
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: tutu.njr10byh.price_statistics.entity

file:
  dir: /home/AAA_Projects/files/Price_Statistics/

server:
  port: 8089
  servlet:
    session:
      timeout: PT30M #过期时间30分钟
    context-path: /price_statistics